[package]
name = "see"
version = "0.0.1"
edition = "2018"

authors = ["wyhaya <wyhaya@gmail.com>"]
description = "Static HTTP file server"
homepage = "https://github.com/wyhaya/see"
repository = "https://github.com/wyhaya/see.git"
license = "MIT"
readme = "README.md"

keywords = [
    "http",
    "static",
    "web",
    "server"
]

[dependencies]
ace = "0.2.0"
async-compression = { version = "0.3.5", features = ["stream", "gzip", "deflate", "brotli"] }
base64 = "0.12.3"
bright = "0.4.0"
dirs = "3.0.1"
futures = "0.3.5"
globset = "0.4.5"
hyper = "0.13.7"
lazy_static = "1.4.0"
logs = { version = "0.0.1", features = ["time"] }
num_cpus = "1.13.0"
percent-encoding = "2.1.0"
rand = "0.7.3"
regex = "1.3.9"
time = "0.1.43"
tokio = { version = "0.2.21", features = ["full"] }
tokio-rustls = "0.14.0"
tokio-util = { version = "0.3.1", features = ["codec"] }
webpki-roots = "0.20.0"
yaml-rust = "0.4.4"

[target.'cfg(unix)'.dependencies]
libc = "0.2.69"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["processthreadsapi"] }